### PR TITLE
Fixing version v2-d

### PR DESCRIPTION
**Pull request by mdrudi**
Here the fixing to gather all the updates related the plotting and the data access. Targeting the release of a version aligned with OceanClimate v2

### CODE REVIEW

**Comment by anto6715** [comment]
@mdrudi I upload some commits to this branch:

- mtplot is enable 
- update daccess to latest version from OceanClimate
- update mtplot to latest version from OceanClimate

**Comment by mdrudi** [comment]
To consider the possibility to document here the Inderface Definition Language which is used to define the interface of a specific method implementation. An additional aspect to describbe is the format of the output log, that in the future should become W3C-PROV complinat. This is something to verify when the code is stable after the inprogress review for the methods _Ocean Patterns/Regimes Indicators_ and _Storm Severity Index_

**Comment by anto6715** [comment]
> An additional aspect to describbe is the format of the output log

About this I have some updates. With the last updates I improve also this code section.
Now there is a python class that handle all the json sections and with a next update in this class will appears also the output format of the json following this syntax: 

https://github.com/CMCC-Foundation/medpetra/blob/0271b32af5018db4b8faa51ae3d038ef0a086067/aux/archpack/src/file.py#L43

On the other hand, we can think to prepare a specific documentation to document the json format and also a simple documentation to explain how to use the relative module

**Comment by mdrudi** [comment]
Question: what attributes are mandatory in the output log ? Requirements of the web app ?

**Comment by mdrudi** [comment]
> 

To add into the repository an example of output log (json file) and in case also the python module which is able to manage the creation of this output file

**Comment by mdrudi** [comment]
> Question: what attributes are mandatory in the output log ? Requirements of the web app ?

Required info are the mandatory as specificed here https://github.com/CMCC-Foundation/bluecloud-mockup_method/tree/fix_v2/log

**Comment by mdrudi** [comment]
To consider the revision of this package to make it not strictly related to BlueCloud

**Comment by mdrudi** [comment]
> > Question: what attributes are mandatory in the output log ? Requirements of the web app ?
> 
> Required info are the mandatory as specificed here https://github.com/CMCC-Foundation/bluecloud-mockup_method/tree/fix_v2/log

- [x] to explain in few words why we assume to be mandatory the two info related the error log and the end time

**Pull request closed without merging**
