### PR TITLE
Dev daccess refactoring

### PR DESCRIPTION
**Pull request by anto6715**
Update of daccess module to improve the code quality.

Changelog:

- Introducing **WorkingDomain** class
- Add support to time frequency parameter
- daccess now can be executed calling it directly (use `python daccess.py -h` to see the argument options)

### CODE REVIEW

**Comment by anto6715** [comment]
> * daccess now can be executed calling it directly (use `python daccess.py -h` to see the argument options)

This point is fundamental to use the daccess module in the test framework

**Comment by mdrudi** [comment]
To review the list of products in https://github.com/CMCC-Foundation/bluecloud-mockup_method/blob/dev_daccess_refactor/download/config/dataset_infrastructures.json

- keep it consistent with the products inside the register
- remove GLOBAL_ANALYSIS_FORECAST_PHY_001_024
- new ID for OCEANCOLOUR_MED_CHL_L4_NRT_OBSERVATIONS_009_041
- to add the WAVE product
- to add the ID of C3S ERA5 (future action)

**Comment by anto6715** [comment]
@mdrudi Since the WEkEO tests are blocked I think that we can close this pull request as it is

**Comment by anto6715** [comment]
Current development is finished.
New code tested with storagehub, WEkEO still not available.

**Pull request merged**
